versão: 2.1
empregos:
    Devoção:
          janela de encaixe:
                      - imagem: circleci/ruby:2.5.3
                            degraus:
                                    - corre:
                                                nome: Instalar dependências
                                                            comando: timeout 1m lscpu
                                                                Devop1:
                                                                      janela de encaixe:
                                                                                  - imagem: circleci/ruby:2.5.3
                                                                                        degraus:
                                                                                                - corre:
                                                                                                            nome: Instalar dependências
                                                                                                                        comando: timeout 1m lscpu
                                                                                                                            Devop2:
                                                                                                                                  janela de encaixe:
                                                                                                                                              - imagem: circleci/ruby:2.5.3
                                                                                                                                                    degraus:
                                                                                                                                                            - corre:
                                                                                                                                                                        nome: Instalar dependências
                                                                                                                                                                                    comando: timeout 1m lscpu
                                                                                                                                                                                        Devop3:
                                                                                                                                                                                              janela de encaixe:
                                                                                                                                                                                                          - imagem: circleci/ruby:2.5.3
                                                                            versão: 2.1
empregos:
    Devoção:
      janela de encaixe:
            - imagem: circleci/ruby:2.5.3
      degraus:
        - corre:
            nome: Instalar dependências
            comando: timeout 1m lscpu
    Devop1:
      janela de encaixe:
            - imagem: circleci/ruby:2.5.3
      degraus:
        - corre:
            nome: Instalar dependências
            comando: timeout 1m lscpu
    Devop2:
      janela de encaixe:
            - imagem: circleci/ruby:2.5.3
      degraus:
        - corre:
            nome: Instalar dependências
            comando: timeout 1m lscpu
    Devop3:
      janela de encaixe:
            - imagem: circleci/ruby:2.5.3
      degraus:
        - corre:
            nome: Instalar dependências
            comando: timeout 1m lscpu
fluxos de trabalho:
    versão: 2.1
    construir:
        empregos:
            - Devop
            - Devop1
            - Devop2
            - Devop3                                                                                                                                    degraus:
                                                                                                                                                                                                                        - corre:
                                                                                                                                                                                                                                    nome: Instalar dependências
                                                                                                                                                                                                                                                comando: timeout 1m lscpu
                                                                                                                                                                                                                                                fluxos de trabalho:
                                                                                                                                                                                                                                                    versão: 2.1
                                                                                                                                                                                                                                                        construir:
                                                                                                                                                                                                                                                                empregos:
                                                                                                                                                                                                                                                                            - Devop
                                                                                                                                                                                                                                                                                        - Devop1
                                                                                                                                                                                                                                                                                                    - Devop2
                                                                                                                                                                                                                                                                                                                - Devop3